services:
  postgres_dev:
    image: postgres:17
    container_name: postgres_dev
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${PORT}:5432"
  postgres_test:
    image: postgres:17
    container_name: postgres_test
    env_file:
     - .env.test
    ports:
      - "5433:5432"
