services:
  postgres_dev:
    image: postgres:17
    container_name: postgres_dev
    env_file:
      - ./app/.env
    ports:
      - "${PORT}:5432"
  postgres_test:
    image: postgres:17
    container_name: postgres_test
    env_file:
     - ./app/.env.test
    ports:
      - "5433:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - postgres_dev
    ports:
      - "8000:8000"
    environment:
      - ENV_FILE=/app/.env
    volumes:
      - ./app:/app
  pytest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_runner
    depends_on:
      - postgres_test
    environment:
      - ENV_FILE=/app/.env.test
    command: ["conda", "run", "-n", "strawberry_fast_api", "tail", "-f", "/dev/null"]
    volumes:
      - ./app:/app

