services:
  postgres_dev:
    image: postgres:17
    container_name: postgres_dev
    env_file:
      - ./app/.env
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - postgres_dev
    ports:
      - "8000:8000"
    environment:
      - ENV_FILE=/app/.env
    command: >
      bash -c "until pg_isready -h postgres_dev -p 5432; do sleep 1; done &&
               conda run -n strawberry_fast_api --no-capture-output fastapi run main.py --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./app:/app

