name: Test

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Create .env.test
        run: |
          cat <<EOF > app/.env.test
          POSTGRES_USER=${{ secrets.TEST_DB_USER }}
          POSTGRES_PASSWORD=${{ secrets.TEST_DB_PASS }}
          POSTGRES_DB=testdb
          HOST=postgres_test
          PORT=5432
          JWT_KEY=${{ secrets.JWT_KEY }}
          JWT_ALGORITHM=HS256
          JWT_EXPIRATION_TIME_MINUTES=15
          EOF

      - name: Build and run tests
        run: docker compose -f docker-compose.test.yml -p test_env up --build --abort-on-container-exit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@f95a404f9265da16dee374e6e9dcb76d3eee88b1
        with:
          file: ./app/coverage.xml
